# Form implementation generated from reading ui file 'generation_password.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GenerationPassword(object):
    def setupUi(self, GenerationPassword):
        GenerationPassword.setObjectName("GenerationPassword")
        GenerationPassword.resize(647, 506)
        GenerationPassword.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.btnGenerate = QtWidgets.QPushButton(parent=GenerationPassword)
        self.btnGenerate.setGeometry(QtCore.QRect(250, 390, 141, 41))
        self.btnGenerate.setObjectName("btnGenerate")
        self.passwordLine = QtWidgets.QLineEdit(parent=GenerationPassword)
        self.passwordLine.setGeometry(QtCore.QRect(190, 80, 261, 41))
        self.passwordLine.setReadOnly(True)
        self.passwordLine.setObjectName("passwordLine")
        self.checkUpper = QtWidgets.QCheckBox(parent=GenerationPassword)
        self.checkUpper.setGeometry(QtCore.QRect(10, 210, 111, 21))
        self.checkUpper.setObjectName("checkUpper")
        self.checkLower = QtWidgets.QCheckBox(parent=GenerationPassword)
        self.checkLower.setGeometry(QtCore.QRect(190, 210, 111, 21))
        self.checkLower.setObjectName("checkLower")
        self.checkDigits = QtWidgets.QCheckBox(parent=GenerationPassword)
        self.checkDigits.setGeometry(QtCore.QRect(580, 210, 111, 21))
        self.checkDigits.setObjectName("checkDigits")
        self.checkSymbols = QtWidgets.QCheckBox(parent=GenerationPassword)
        self.checkSymbols.setGeometry(QtCore.QRect(400, 210, 111, 21))
        self.checkSymbols.setObjectName("checkSymbols")
        self.passwordGrade = QtWidgets.QLabel(parent=GenerationPassword)
        self.passwordGrade.setEnabled(True)
        self.passwordGrade.setGeometry(QtCore.QRect(460, 80, 161, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 4))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 4))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.passwordGrade.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.passwordGrade.setFont(font)
        self.passwordGrade.setText("")
        self.passwordGrade.setObjectName("passwordGrade")
        self.lenghtSlider = QtWidgets.QSlider(parent=GenerationPassword)
        self.lenghtSlider.setGeometry(QtCore.QRect(180, 300, 291, 21))
        self.lenghtSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.lenghtSlider.setObjectName("lenghtSlider")
        self.btnBack = QtWidgets.QPushButton(parent=GenerationPassword)
        self.btnBack.setGeometry(QtCore.QRect(0, 0, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnBack.setFont(font)
        self.btnBack.setObjectName("btnBack")
        self.btnSave = QtWidgets.QPushButton(parent=GenerationPassword)
        self.btnSave.setGeometry(QtCore.QRect(40, 90, 101, 31))
        self.btnSave.setObjectName("btnSave")

        self.retranslateUi(GenerationPassword)
        QtCore.QMetaObject.connectSlotsByName(GenerationPassword)

    def retranslateUi(self, GenerationPassword):
        _translate = QtCore.QCoreApplication.translate
        GenerationPassword.setWindowTitle(_translate("GenerationPassword", "Генератор пароля"))
        self.btnGenerate.setText(_translate("GenerationPassword", "Сгенерировать"))
        self.passwordLine.setText(_translate("GenerationPassword", "Выберите длину пароля: 4"))
        self.checkUpper.setText(_translate("GenerationPassword", "Верхний регистр"))
        self.checkLower.setText(_translate("GenerationPassword", "Нижний Регистр"))
        self.checkDigits.setText(_translate("GenerationPassword", "Цифры"))
        self.checkSymbols.setText(_translate("GenerationPassword", "Спец. Символы"))
        self.btnBack.setText(_translate("GenerationPassword", "<-"))
        self.btnSave.setText(_translate("GenerationPassword", "Сохранить"))
