# Form implementation generated from reading ui file 'home_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(415, 518)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        HomePage.setFont(font)
        self.name = QtWidgets.QLabel(parent=HomePage)
        self.name.setGeometry(QtCore.QRect(120, 40, 291, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 243))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 243))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        self.name.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.btnLogin = QtWidgets.QPushButton(parent=HomePage)
        self.btnLogin.setGeometry(QtCore.QRect(-10, 190, 431, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName("btnLogin")
        self.btnRegister = QtWidgets.QPushButton(parent=HomePage)
        self.btnRegister.setGeometry(QtCore.QRect(-10, 280, 431, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btnRegister.setFont(font)
        self.btnRegister.setObjectName("btnRegister")
        self.btnWithoutReg = QtWidgets.QPushButton(parent=HomePage)
        self.btnWithoutReg.setGeometry(QtCore.QRect(-10, 370, 431, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btnWithoutReg.setFont(font)
        self.btnWithoutReg.setObjectName("btnWithoutReg")

        self.retranslateUi(HomePage)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "Form"))
        self.name.setText(_translate("HomePage", "Pass Guard"))
        self.btnLogin.setText(_translate("HomePage", "Войти"))
        self.btnRegister.setText(_translate("HomePage", "Зарегистрироваться"))
        self.btnWithoutReg.setText(_translate("HomePage", "Войти Без Регистрации"))
