# Form implementation generated from reading ui file 'table_passwords.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DataBase(object):
    def setupUi(self, DataBase):
        DataBase.setObjectName("DataBase")
        DataBase.resize(794, 814)
        self.verticalLayout = QtWidgets.QVBoxLayout(DataBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnBack = QtWidgets.QPushButton(parent=DataBase)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnBack.setFont(font)
        self.btnBack.setObjectName("btnBack")
        self.verticalLayout.addWidget(self.btnBack)
        self.table = QtWidgets.QTableWidget(parent=DataBase)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.table)
        self.btnClear = QtWidgets.QPushButton(parent=DataBase)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.verticalLayout.addWidget(self.btnClear)

        self.retranslateUi(DataBase)
        QtCore.QMetaObject.connectSlotsByName(DataBase)

    def retranslateUi(self, DataBase):
        _translate = QtCore.QCoreApplication.translate
        DataBase.setWindowTitle(_translate("DataBase", "База Паролей"))
        self.btnBack.setText(_translate("DataBase", "<-"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("DataBase", "id_user"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("DataBase", "user"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("DataBase", "password"))
        self.btnClear.setText(_translate("DataBase", "Очистить"))
