# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(622, 312)
        self.linePassword = QtWidgets.QLineEdit(parent=Registration)
        self.linePassword.setGeometry(QtCore.QRect(230, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.linePassword.setFont(font)
        self.linePassword.setObjectName("linePassword")
        self.lineName = QtWidgets.QLineEdit(parent=Registration)
        self.lineName.setGeometry(QtCore.QRect(230, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineName.setFont(font)
        self.lineName.setObjectName("lineName")
        self.labelName = QtWidgets.QLabel(parent=Registration)
        self.labelName.setGeometry(QtCore.QRect(130, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.labelPassword = QtWidgets.QLabel(parent=Registration)
        self.labelPassword.setGeometry(QtCore.QRect(130, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPassword.setFont(font)
        self.labelPassword.setObjectName("labelPassword")
        self.btnReg = QtWidgets.QPushButton(parent=Registration)
        self.btnReg.setGeometry(QtCore.QRect(270, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnReg.setFont(font)
        self.btnReg.setObjectName("btnReg")
        self.btnBack = QtWidgets.QPushButton(parent=Registration)
        self.btnBack.setGeometry(QtCore.QRect(0, 0, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnBack.setFont(font)
        self.btnBack.setObjectName("btnBack")

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Form"))
        self.labelName.setText(_translate("Registration", "Имя:"))
        self.labelPassword.setText(_translate("Registration", "Пароль:"))
        self.btnReg.setText(_translate("Registration", "Войти"))
        self.btnBack.setText(_translate("Registration", "<-"))
